# Generated by Django 6.1.1 on 2026-09-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_more_role_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
        # Must run after ventes.0007_list_views: that migration's `CREATE
        # VIEW` SQL references the old `accounts_customer` table name, so
        # this rename can't happen first or the view creation fails.
        ('ventes', '0007_list_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='role_permissions', related_name='roles', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='user_roles', related_name='users', to='accounts.role'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
