# Generated by Django 6.1.1 on 2026-09-03 19:29

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_reference_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('cancelled', 'Annulée')], default='draft', max_length=50),
        ),
    ]
