# Generated by Django 6.1.1 on 2026-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_reference_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='currency',
            field=models.CharField(choices=[('MGA', 'Ariary malgache'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='MGA', max_length=3),
        ),
        migrations.AddField(
            model_name='vente',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='subtotal_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='tva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
