# Generated by Django 6.1.1 on 2026-09-30 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_drop_unused_auth_group_tables'),
        ('ventes', '0010_seed_fournisseur_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('MGA', 'Ariary malgache'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='MGA', max_length=3)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='accounts.customer')),
            ],
            options={
                'db_table': 'bon_commande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonCommandeLigne',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ventes.boncommande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ventes.product')),
            ],
            options={
                'db_table': 'bon_commande_ligne',
            },
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS bon_commande_id_seq;",
            reverse_sql="DROP SEQUENCE IF EXISTS bon_commande_id_seq;",
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS bon_commande_ligne_id_seq;",
            reverse_sql="DROP SEQUENCE IF EXISTS bon_commande_ligne_id_seq;",
        ),

    ]
