# Generated by Django 6.1.1 on 2026-10-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userpermissionoverride'),
        ('ventes', '0012_seed_bon_commande_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommandeListView',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_delivery_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bon_commande_list_view',
                'ordering': ['-created_at'],
                'managed': False,
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.RunSQL(
            sql='CREATE OR REPLACE VIEW bon_commande_list_view AS\nSELECT\n    b.id,\n    b.customer_id AS customer,\n    c.name AS customer_name,\n    b.currency,\n    b.discount_percent,\n    b.expected_delivery_date,\n    b.created_at,\n    b.updated_at\nFROM bon_commande b\nINNER JOIN customer c ON c.id = b.customer_id;',
            reverse_sql='DROP VIEW IF EXISTS bon_commande_list_view;',
        ),
    ]
