# Generated by Django 6.1.1 on 2026-10-03 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0013_bon_commande_list_view_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommandeLigneListView',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bon_commande', models.ForeignKey(db_column='bon_commande_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lines', to='ventes.boncommandelistview')),
                ('product', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tva_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'bon_commande_ligne_list_view',
                'managed': False,
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.RunSQL(
            sql='CREATE OR REPLACE VIEW bon_commande_ligne_list_view AS\nSELECT\n    l.id,\n    l.bon_commande_id,\n    l.product_id AS product,\n    p.name AS product_name,\n    p.sku AS product_sku,\n    l.quantity,\n    l.unit_price,\n    l.discount_percent,\n    l.tva_rate\nFROM bon_commande_ligne l\nINNER JOIN product p ON p.id = l.product_id;',
            reverse_sql='DROP VIEW IF EXISTS bon_commande_ligne_list_view;',
        ),
    ]
